// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Неиспользуемое поле \"BMP\".", Justification = "<Ожидание>", Scope = "member", Target = "~F:ImageEditor.ImgEditor.BMP")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"int.ToString()\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"ImageCutter.ImageCutter(MainWindow, int, int)\" на вызов \"int.ToString(IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.ImageCutter.#ctor(ImageEditor.MainWindow,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"Convert.ToInt32(string)\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"ImageCutter.BtnOk_Click(object, EventArgs)\" на вызов \"Convert.ToInt32(string, IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.ImageCutter.BtnOk_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Метод \"void ImageCutter.BtnOk_Click(object sender, EventArgs e)\" передает строку-литерал, как параметр \"text\" при вызове \"DialogResult MessageBox.Show(string text)\". Вместо этого выполните поиск следующих строк в таблице ресурсов: \"Wrong data!\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.ImageCutter.BtnOk_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"Convert.ToInt32(string)\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"ImageCutter.TextOnNumberChecker(TextBox)\" на вызов \"Convert.ToInt32(string, IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.ImageCutter.TextOnNumberChecker(System.Windows.Forms.TextBox)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Метод \"void ImageCutter.TextOnNumberChecker(TextBox textBox)\" передает строку-литерал, как параметр \"value\" при вызове \"void TextBox.Text.set\". Вместо этого выполните поиск следующих строк в таблице ресурсов: \"0\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.ImageCutter.TextOnNumberChecker(System.Windows.Forms.TextBox)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"Convert.ToByte(string)\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"MainWindow.btnDrc_Click(object, EventArgs)\" на вызов \"Convert.ToByte(string, IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.btnDrc_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"Convert.ToInt32(string)\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"MainWindow.btnLinearContrast_Click(object, EventArgs)\" на вызов \"Convert.ToInt32(string, IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.btnLinearContrast_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"Convert.ToInt32(string)\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"MainWindow.btnLog_Click(object, EventArgs)\" на вызов \"Convert.ToInt32(string, IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.btnLog_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Вызовите System.IDisposable.Dispose для объекта, созданного \"new SaveFileDialog()\", прежде чем все ссылки на него будут вне области действия.", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.btnSaveImage_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"Convert.ToInt32(string)\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"MainWindow.CheckTextBox(TextBox)\" на вызов \"Convert.ToInt32(string, IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.CheckTextBox(System.Windows.Forms.TextBox)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Метод \"void MainWindow.CheckTextBox(TextBox textBox)\" передает строку-литерал, как параметр \"text\" при вызове \"DialogResult MessageBox.Show(string text)\". Вместо этого выполните поиск следующих строк в таблице ресурсов: \"Wrong Entering\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.CheckTextBox(System.Windows.Forms.TextBox)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"byte.ToString()\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"MainWindow.setMinMaxBrightnessInfo()\" на вызов \"byte.ToString(IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.setMinMaxBrightnessInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:Поведение \"int.ToString()\" может изменяться в зависимости от параметров языкового стандарта текущего пользователя. Замените этот вызов в \"MainWindow.WriteImageInfo()\" на вызов \"int.ToString(IFormatProvider)\".", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.MainWindow.WriteImageInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Вызовите System.IDisposable.Dispose для объекта, созданного \"new MainWindow()\", прежде чем все ссылки на него будут вне области действия.", Justification = "<Ожидание>", Scope = "member", Target = "~M:ImageEditor.Program.Main")]